name: checks
on:
  pull_request:
  push:
    branches:
      - "main"
jobs:
  check-golang:
    runs-on: ubuntu-latest
    name: Golang and UI Linting
    steps:
      - uses: actions/checkout@v4
      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.golang-version }}"
          check-latest: true
          cache: true

      - name: Tidy Go modules and check for changes
        run: make tidy && git diff --exit-code

      - name: Run GolangCI Lint
        uses: golangci/golangci-lint-action@v6.5.0
        with:
          version: v1.60.3
          args: --timeout 10m0s --go ${{ env.golang-version }}

  format:
    runs-on: ubuntu-latest
    name: Documentation Formatting Check
    steps:
      - uses: actions/checkout@v4

      - name: Import environment variables from file
        run: cat ".github/env" >> $GITHUB_ENV

      - uses: actions/setup-go@v5
        with:
          go-version: "${{ env.golang-version }}"
          check-latest: true
          cache: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: "${{ env.golang-version }}"
          check-latest: true

      - name: Tidy Go modules
        run: make tidy

      - name: Check Documentation
        run: make check-docs
